### ISSUE TITLE
Can't compile on ubuntu

### ISSUE THREAD

**Issue by mzingl** [krivenko/som#1]
Hi,
I have the newest TRIQS version installed. I tried to compile the som code, but I get the following error:

[  7%] Building CXX object c++/CMakeFiles/som_c.dir/som_core.cpp.o
In file included from /home/manuel/Tools/SOMAC/src/c++/kernels/base.hpp:29:0,
                 from /home/manuel/Tools/SOMAC/src/c++/som_core.hpp:33,
                 from /home/manuel/Tools/SOMAC/src/c++/som_core.cpp:23:
/home/manuel/Tools/SOMAC/src/c++/kernels/../config_update.hpp: In member function ‘void som::config_update::apply()’:
/home/manuel/Tools/SOMAC/src/c++/kernels/../config_update.hpp:112:18: error: ‘cbegin’ is not a member of ‘std’
   auto rect_it = std::cbegin(new_rects);
                  ^
/home/manuel/Tools/SOMAC/src/c++/kernels/../config_update.hpp:112:18: note: suggested alternative:
In file included from /home/manuel/Tools/TRIQS/include/triqs/gfs.hpp:48:0,
                 from /home/manuel/Tools/SOMAC/src/c++/som_core.hpp:26,
                 from /home/manuel/Tools/SOMAC/src/c++/som_core.cpp:23:
/home/manuel/Tools/TRIQS/include/triqs/gfs/impl/block_gf_iterator.hpp:65:102: note:   ‘triqs::gfs::cbegin’
  template <typename G> std14::enable_if_t<is_block_gf_or_view<G>::value, block_gf_iterator<G const>> cbegin(G const &bgf) {
                                                                                                      ^
In file included from /home/manuel/Tools/SOMAC/src/c++/som_core.hpp:33:0,
                 from /home/manuel/Tools/SOMAC/src/c++/som_core.cpp:23:
/home/manuel/Tools/SOMAC/src/c++/kernels/base.hpp: In member function ‘const ResultType& som::kernel_base<Derived, ResultType>::operator()(const som::config_update&) const’:
/home/manuel/Tools/SOMAC/src/c++/kernels/base.hpp:124:19: error: ‘cbegin’ is not a member of ‘std’
    auto rect_it = std::cbegin(cu.new_rects);
                   ^
/home/manuel/Tools/SOMAC/src/c++/kernels/base.hpp:124:19: note: suggested alternative:
In file included from /home/manuel/Tools/TRIQS/include/triqs/gfs.hpp:48:0,
                 from /home/manuel/Tools/SOMAC/src/c++/som_core.hpp:26,
                 from /home/manuel/Tools/SOMAC/src/c++/som_core.cpp:23:
/home/manuel/Tools/TRIQS/include/triqs/gfs/impl/block_gf_iterator.hpp:65:102: note:   ‘triqs::gfs::cbegin’
  template <typename G> std14::enable_if_t<is_block_gf_or_view<G>::value, block_gf_iterator<G const>> cbegin(G const &bgf) {
                                                                                                      ^
make[2]: **\* [c++/CMakeFiles/som_c.dir/som_core.cpp.o] Error 1
make[1]: **\* [c++/CMakeFiles/som_c.dir/all] Error 2
make: **\* [all] Error 2

Thanks,
Manuel

**Comment by krivenko** [comment]
Hi Manuel,
What is your compiler? Has TRIQS been built in the C++14 mode?

**Comment by mzingl** [comment]
GNU 4.9.3
C++14 mode is on

**Comment by krivenko** [comment]
`std::cbegin()` was introduced in C++14, which is supported by gcc 4.9 to a limited extent. This particular feature was added only in gcc 5.1.
Anyhow, I'll fix it soon.
